name: Deploy to EC2
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      
      - name: Copy files to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "Deploying to host: $HOST"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          
          # Copy files to EC2
          scp -o StrictHostKeyChecking=no -i private_key index.js package.json ec2-user@$HOST:~/my-app/
          
          # Install dependencies and restart app
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@$HOST '
            cd ~/my-app
            npm install
            pm2 restart my-app-db || pm2 start index.js --name my-app-db
            pm2 save
            echo "Deployment complete!"
          '
